
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  grupo: 'grupo',
  funcionario: 'funcionario',
  time: 'time',
  funcionario_grupo: 'funcionario_grupo',
  user_app: 'user_app',
  aplicacao: 'aplicacao',
  aplicacao_user_app: 'aplicacao_user_app'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const GrupoScalarFieldEnum = {
  id_grupo: 'id_grupo',
  nome: 'nome'
} as const

export type GrupoScalarFieldEnum = (typeof GrupoScalarFieldEnum)[keyof typeof GrupoScalarFieldEnum]


export const FuncionarioScalarFieldEnum = {
  matricula: 'matricula',
  nome: 'nome',
  username: 'username',
  senha: 'senha',
  email: 'email'
} as const

export type FuncionarioScalarFieldEnum = (typeof FuncionarioScalarFieldEnum)[keyof typeof FuncionarioScalarFieldEnum]


export const TimeScalarFieldEnum = {
  id_time: 'id_time',
  nome: 'nome',
  id_grupo: 'id_grupo',
  pdl: 'pdl'
} as const

export type TimeScalarFieldEnum = (typeof TimeScalarFieldEnum)[keyof typeof TimeScalarFieldEnum]


export const Funcionario_grupoScalarFieldEnum = {
  matricula_funcionario: 'matricula_funcionario',
  id_grupo: 'id_grupo'
} as const

export type Funcionario_grupoScalarFieldEnum = (typeof Funcionario_grupoScalarFieldEnum)[keyof typeof Funcionario_grupoScalarFieldEnum]


export const User_appScalarFieldEnum = {
  id_user_app: 'id_user_app',
  username: 'username',
  senha: 'senha',
  matricula_funcionario: 'matricula_funcionario'
} as const

export type User_appScalarFieldEnum = (typeof User_appScalarFieldEnum)[keyof typeof User_appScalarFieldEnum]


export const AplicacaoScalarFieldEnum = {
  id_app: 'id_app',
  component_tag: 'component_tag',
  nome: 'nome',
  id_time: 'id_time'
} as const

export type AplicacaoScalarFieldEnum = (typeof AplicacaoScalarFieldEnum)[keyof typeof AplicacaoScalarFieldEnum]


export const Aplicacao_user_appScalarFieldEnum = {
  id_app: 'id_app',
  id_user_app: 'id_user_app'
} as const

export type Aplicacao_user_appScalarFieldEnum = (typeof Aplicacao_user_appScalarFieldEnum)[keyof typeof Aplicacao_user_appScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

