
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `funcionario` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model funcionario
 * 
 */
export type funcionarioModel = runtime.Types.Result.DefaultSelection<Prisma.$funcionarioPayload>

export type AggregateFuncionario = {
  _count: FuncionarioCountAggregateOutputType | null
  _min: FuncionarioMinAggregateOutputType | null
  _max: FuncionarioMaxAggregateOutputType | null
}

export type FuncionarioMinAggregateOutputType = {
  matricula: string | null
  nome: string | null
  username: string | null
  senha: string | null
  email: string | null
}

export type FuncionarioMaxAggregateOutputType = {
  matricula: string | null
  nome: string | null
  username: string | null
  senha: string | null
  email: string | null
}

export type FuncionarioCountAggregateOutputType = {
  matricula: number
  nome: number
  username: number
  senha: number
  email: number
  _all: number
}


export type FuncionarioMinAggregateInputType = {
  matricula?: true
  nome?: true
  username?: true
  senha?: true
  email?: true
}

export type FuncionarioMaxAggregateInputType = {
  matricula?: true
  nome?: true
  username?: true
  senha?: true
  email?: true
}

export type FuncionarioCountAggregateInputType = {
  matricula?: true
  nome?: true
  username?: true
  senha?: true
  email?: true
  _all?: true
}

export type FuncionarioAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which funcionario to aggregate.
   */
  where?: Prisma.funcionarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of funcionarios to fetch.
   */
  orderBy?: Prisma.funcionarioOrderByWithRelationInput | Prisma.funcionarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.funcionarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` funcionarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` funcionarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned funcionarios
  **/
  _count?: true | FuncionarioCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FuncionarioMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FuncionarioMaxAggregateInputType
}

export type GetFuncionarioAggregateType<T extends FuncionarioAggregateArgs> = {
      [P in keyof T & keyof AggregateFuncionario]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFuncionario[P]>
    : Prisma.GetScalarType<T[P], AggregateFuncionario[P]>
}




export type funcionarioGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.funcionarioWhereInput
  orderBy?: Prisma.funcionarioOrderByWithAggregationInput | Prisma.funcionarioOrderByWithAggregationInput[]
  by: Prisma.FuncionarioScalarFieldEnum[] | Prisma.FuncionarioScalarFieldEnum
  having?: Prisma.funcionarioScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FuncionarioCountAggregateInputType | true
  _min?: FuncionarioMinAggregateInputType
  _max?: FuncionarioMaxAggregateInputType
}

export type FuncionarioGroupByOutputType = {
  matricula: string
  nome: string
  username: string
  senha: string
  email: string | null
  _count: FuncionarioCountAggregateOutputType | null
  _min: FuncionarioMinAggregateOutputType | null
  _max: FuncionarioMaxAggregateOutputType | null
}

type GetFuncionarioGroupByPayload<T extends funcionarioGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FuncionarioGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FuncionarioGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FuncionarioGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FuncionarioGroupByOutputType[P]>
      }
    >
  >



export type funcionarioWhereInput = {
  AND?: Prisma.funcionarioWhereInput | Prisma.funcionarioWhereInput[]
  OR?: Prisma.funcionarioWhereInput[]
  NOT?: Prisma.funcionarioWhereInput | Prisma.funcionarioWhereInput[]
  matricula?: Prisma.StringFilter<"funcionario"> | string
  nome?: Prisma.StringFilter<"funcionario"> | string
  username?: Prisma.StringFilter<"funcionario"> | string
  senha?: Prisma.StringFilter<"funcionario"> | string
  email?: Prisma.StringNullableFilter<"funcionario"> | string | null
  funcionario_grupos?: Prisma.Funcionario_grupoListRelationFilter
  user_apps?: Prisma.User_appListRelationFilter
}

export type funcionarioOrderByWithRelationInput = {
  matricula?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  funcionario_grupos?: Prisma.funcionario_grupoOrderByRelationAggregateInput
  user_apps?: Prisma.user_appOrderByRelationAggregateInput
}

export type funcionarioWhereUniqueInput = Prisma.AtLeast<{
  matricula?: string
  username?: string
  AND?: Prisma.funcionarioWhereInput | Prisma.funcionarioWhereInput[]
  OR?: Prisma.funcionarioWhereInput[]
  NOT?: Prisma.funcionarioWhereInput | Prisma.funcionarioWhereInput[]
  nome?: Prisma.StringFilter<"funcionario"> | string
  senha?: Prisma.StringFilter<"funcionario"> | string
  email?: Prisma.StringNullableFilter<"funcionario"> | string | null
  funcionario_grupos?: Prisma.Funcionario_grupoListRelationFilter
  user_apps?: Prisma.User_appListRelationFilter
}, "matricula" | "username">

export type funcionarioOrderByWithAggregationInput = {
  matricula?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.funcionarioCountOrderByAggregateInput
  _max?: Prisma.funcionarioMaxOrderByAggregateInput
  _min?: Prisma.funcionarioMinOrderByAggregateInput
}

export type funcionarioScalarWhereWithAggregatesInput = {
  AND?: Prisma.funcionarioScalarWhereWithAggregatesInput | Prisma.funcionarioScalarWhereWithAggregatesInput[]
  OR?: Prisma.funcionarioScalarWhereWithAggregatesInput[]
  NOT?: Prisma.funcionarioScalarWhereWithAggregatesInput | Prisma.funcionarioScalarWhereWithAggregatesInput[]
  matricula?: Prisma.StringWithAggregatesFilter<"funcionario"> | string
  nome?: Prisma.StringWithAggregatesFilter<"funcionario"> | string
  username?: Prisma.StringWithAggregatesFilter<"funcionario"> | string
  senha?: Prisma.StringWithAggregatesFilter<"funcionario"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"funcionario"> | string | null
}

export type funcionarioCreateInput = {
  matricula: string
  nome: string
  username: string
  senha: string
  email?: string | null
  funcionario_grupos?: Prisma.funcionario_grupoCreateNestedManyWithoutFuncionarioInput
  user_apps?: Prisma.user_appCreateNestedManyWithoutFuncionarioInput
}

export type funcionarioUncheckedCreateInput = {
  matricula: string
  nome: string
  username: string
  senha: string
  email?: string | null
  funcionario_grupos?: Prisma.funcionario_grupoUncheckedCreateNestedManyWithoutFuncionarioInput
  user_apps?: Prisma.user_appUncheckedCreateNestedManyWithoutFuncionarioInput
}

export type funcionarioUpdateInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcionario_grupos?: Prisma.funcionario_grupoUpdateManyWithoutFuncionarioNestedInput
  user_apps?: Prisma.user_appUpdateManyWithoutFuncionarioNestedInput
}

export type funcionarioUncheckedUpdateInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcionario_grupos?: Prisma.funcionario_grupoUncheckedUpdateManyWithoutFuncionarioNestedInput
  user_apps?: Prisma.user_appUncheckedUpdateManyWithoutFuncionarioNestedInput
}

export type funcionarioCreateManyInput = {
  matricula: string
  nome: string
  username: string
  senha: string
  email?: string | null
}

export type funcionarioUpdateManyMutationInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type funcionarioUncheckedUpdateManyInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type funcionarioCountOrderByAggregateInput = {
  matricula?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type funcionarioMaxOrderByAggregateInput = {
  matricula?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type funcionarioMinOrderByAggregateInput = {
  matricula?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type FuncionarioScalarRelationFilter = {
  is?: Prisma.funcionarioWhereInput
  isNot?: Prisma.funcionarioWhereInput
}

export type FuncionarioNullableScalarRelationFilter = {
  is?: Prisma.funcionarioWhereInput | null
  isNot?: Prisma.funcionarioWhereInput | null
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type funcionarioCreateNestedOneWithoutFuncionario_gruposInput = {
  create?: Prisma.XOR<Prisma.funcionarioCreateWithoutFuncionario_gruposInput, Prisma.funcionarioUncheckedCreateWithoutFuncionario_gruposInput>
  connectOrCreate?: Prisma.funcionarioCreateOrConnectWithoutFuncionario_gruposInput
  connect?: Prisma.funcionarioWhereUniqueInput
}

export type funcionarioUpdateOneRequiredWithoutFuncionario_gruposNestedInput = {
  create?: Prisma.XOR<Prisma.funcionarioCreateWithoutFuncionario_gruposInput, Prisma.funcionarioUncheckedCreateWithoutFuncionario_gruposInput>
  connectOrCreate?: Prisma.funcionarioCreateOrConnectWithoutFuncionario_gruposInput
  upsert?: Prisma.funcionarioUpsertWithoutFuncionario_gruposInput
  connect?: Prisma.funcionarioWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.funcionarioUpdateToOneWithWhereWithoutFuncionario_gruposInput, Prisma.funcionarioUpdateWithoutFuncionario_gruposInput>, Prisma.funcionarioUncheckedUpdateWithoutFuncionario_gruposInput>
}

export type funcionarioCreateNestedOneWithoutUser_appsInput = {
  create?: Prisma.XOR<Prisma.funcionarioCreateWithoutUser_appsInput, Prisma.funcionarioUncheckedCreateWithoutUser_appsInput>
  connectOrCreate?: Prisma.funcionarioCreateOrConnectWithoutUser_appsInput
  connect?: Prisma.funcionarioWhereUniqueInput
}

export type funcionarioUpdateOneWithoutUser_appsNestedInput = {
  create?: Prisma.XOR<Prisma.funcionarioCreateWithoutUser_appsInput, Prisma.funcionarioUncheckedCreateWithoutUser_appsInput>
  connectOrCreate?: Prisma.funcionarioCreateOrConnectWithoutUser_appsInput
  upsert?: Prisma.funcionarioUpsertWithoutUser_appsInput
  disconnect?: Prisma.funcionarioWhereInput | boolean
  delete?: Prisma.funcionarioWhereInput | boolean
  connect?: Prisma.funcionarioWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.funcionarioUpdateToOneWithWhereWithoutUser_appsInput, Prisma.funcionarioUpdateWithoutUser_appsInput>, Prisma.funcionarioUncheckedUpdateWithoutUser_appsInput>
}

export type funcionarioCreateWithoutFuncionario_gruposInput = {
  matricula: string
  nome: string
  username: string
  senha: string
  email?: string | null
  user_apps?: Prisma.user_appCreateNestedManyWithoutFuncionarioInput
}

export type funcionarioUncheckedCreateWithoutFuncionario_gruposInput = {
  matricula: string
  nome: string
  username: string
  senha: string
  email?: string | null
  user_apps?: Prisma.user_appUncheckedCreateNestedManyWithoutFuncionarioInput
}

export type funcionarioCreateOrConnectWithoutFuncionario_gruposInput = {
  where: Prisma.funcionarioWhereUniqueInput
  create: Prisma.XOR<Prisma.funcionarioCreateWithoutFuncionario_gruposInput, Prisma.funcionarioUncheckedCreateWithoutFuncionario_gruposInput>
}

export type funcionarioUpsertWithoutFuncionario_gruposInput = {
  update: Prisma.XOR<Prisma.funcionarioUpdateWithoutFuncionario_gruposInput, Prisma.funcionarioUncheckedUpdateWithoutFuncionario_gruposInput>
  create: Prisma.XOR<Prisma.funcionarioCreateWithoutFuncionario_gruposInput, Prisma.funcionarioUncheckedCreateWithoutFuncionario_gruposInput>
  where?: Prisma.funcionarioWhereInput
}

export type funcionarioUpdateToOneWithWhereWithoutFuncionario_gruposInput = {
  where?: Prisma.funcionarioWhereInput
  data: Prisma.XOR<Prisma.funcionarioUpdateWithoutFuncionario_gruposInput, Prisma.funcionarioUncheckedUpdateWithoutFuncionario_gruposInput>
}

export type funcionarioUpdateWithoutFuncionario_gruposInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_apps?: Prisma.user_appUpdateManyWithoutFuncionarioNestedInput
}

export type funcionarioUncheckedUpdateWithoutFuncionario_gruposInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user_apps?: Prisma.user_appUncheckedUpdateManyWithoutFuncionarioNestedInput
}

export type funcionarioCreateWithoutUser_appsInput = {
  matricula: string
  nome: string
  username: string
  senha: string
  email?: string | null
  funcionario_grupos?: Prisma.funcionario_grupoCreateNestedManyWithoutFuncionarioInput
}

export type funcionarioUncheckedCreateWithoutUser_appsInput = {
  matricula: string
  nome: string
  username: string
  senha: string
  email?: string | null
  funcionario_grupos?: Prisma.funcionario_grupoUncheckedCreateNestedManyWithoutFuncionarioInput
}

export type funcionarioCreateOrConnectWithoutUser_appsInput = {
  where: Prisma.funcionarioWhereUniqueInput
  create: Prisma.XOR<Prisma.funcionarioCreateWithoutUser_appsInput, Prisma.funcionarioUncheckedCreateWithoutUser_appsInput>
}

export type funcionarioUpsertWithoutUser_appsInput = {
  update: Prisma.XOR<Prisma.funcionarioUpdateWithoutUser_appsInput, Prisma.funcionarioUncheckedUpdateWithoutUser_appsInput>
  create: Prisma.XOR<Prisma.funcionarioCreateWithoutUser_appsInput, Prisma.funcionarioUncheckedCreateWithoutUser_appsInput>
  where?: Prisma.funcionarioWhereInput
}

export type funcionarioUpdateToOneWithWhereWithoutUser_appsInput = {
  where?: Prisma.funcionarioWhereInput
  data: Prisma.XOR<Prisma.funcionarioUpdateWithoutUser_appsInput, Prisma.funcionarioUncheckedUpdateWithoutUser_appsInput>
}

export type funcionarioUpdateWithoutUser_appsInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcionario_grupos?: Prisma.funcionario_grupoUpdateManyWithoutFuncionarioNestedInput
}

export type funcionarioUncheckedUpdateWithoutUser_appsInput = {
  matricula?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  funcionario_grupos?: Prisma.funcionario_grupoUncheckedUpdateManyWithoutFuncionarioNestedInput
}


/**
 * Count Type FuncionarioCountOutputType
 */

export type FuncionarioCountOutputType = {
  funcionario_grupos: number
  user_apps: number
}

export type FuncionarioCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  funcionario_grupos?: boolean | FuncionarioCountOutputTypeCountFuncionario_gruposArgs
  user_apps?: boolean | FuncionarioCountOutputTypeCountUser_appsArgs
}

/**
 * FuncionarioCountOutputType without action
 */
export type FuncionarioCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuncionarioCountOutputType
   */
  select?: Prisma.FuncionarioCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FuncionarioCountOutputType without action
 */
export type FuncionarioCountOutputTypeCountFuncionario_gruposArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.funcionario_grupoWhereInput
}

/**
 * FuncionarioCountOutputType without action
 */
export type FuncionarioCountOutputTypeCountUser_appsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_appWhereInput
}


export type funcionarioSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  matricula?: boolean
  nome?: boolean
  username?: boolean
  senha?: boolean
  email?: boolean
  funcionario_grupos?: boolean | Prisma.funcionario$funcionario_gruposArgs<ExtArgs>
  user_apps?: boolean | Prisma.funcionario$user_appsArgs<ExtArgs>
  _count?: boolean | Prisma.FuncionarioCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["funcionario"]>

export type funcionarioSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  matricula?: boolean
  nome?: boolean
  username?: boolean
  senha?: boolean
  email?: boolean
}, ExtArgs["result"]["funcionario"]>

export type funcionarioSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  matricula?: boolean
  nome?: boolean
  username?: boolean
  senha?: boolean
  email?: boolean
}, ExtArgs["result"]["funcionario"]>

export type funcionarioSelectScalar = {
  matricula?: boolean
  nome?: boolean
  username?: boolean
  senha?: boolean
  email?: boolean
}

export type funcionarioOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"matricula" | "nome" | "username" | "senha" | "email", ExtArgs["result"]["funcionario"]>
export type funcionarioInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  funcionario_grupos?: boolean | Prisma.funcionario$funcionario_gruposArgs<ExtArgs>
  user_apps?: boolean | Prisma.funcionario$user_appsArgs<ExtArgs>
  _count?: boolean | Prisma.FuncionarioCountOutputTypeDefaultArgs<ExtArgs>
}
export type funcionarioIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type funcionarioIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $funcionarioPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "funcionario"
  objects: {
    funcionario_grupos: Prisma.$funcionario_grupoPayload<ExtArgs>[]
    user_apps: Prisma.$user_appPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    matricula: string
    nome: string
    username: string
    senha: string
    email: string | null
  }, ExtArgs["result"]["funcionario"]>
  composites: {}
}

export type funcionarioGetPayload<S extends boolean | null | undefined | funcionarioDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$funcionarioPayload, S>

export type funcionarioCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<funcionarioFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FuncionarioCountAggregateInputType | true
  }

export interface funcionarioDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['funcionario'], meta: { name: 'funcionario' } }
  /**
   * Find zero or one Funcionario that matches the filter.
   * @param {funcionarioFindUniqueArgs} args - Arguments to find a Funcionario
   * @example
   * // Get one Funcionario
   * const funcionario = await prisma.funcionario.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends funcionarioFindUniqueArgs>(args: Prisma.SelectSubset<T, funcionarioFindUniqueArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Funcionario that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {funcionarioFindUniqueOrThrowArgs} args - Arguments to find a Funcionario
   * @example
   * // Get one Funcionario
   * const funcionario = await prisma.funcionario.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends funcionarioFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, funcionarioFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Funcionario that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {funcionarioFindFirstArgs} args - Arguments to find a Funcionario
   * @example
   * // Get one Funcionario
   * const funcionario = await prisma.funcionario.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends funcionarioFindFirstArgs>(args?: Prisma.SelectSubset<T, funcionarioFindFirstArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Funcionario that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {funcionarioFindFirstOrThrowArgs} args - Arguments to find a Funcionario
   * @example
   * // Get one Funcionario
   * const funcionario = await prisma.funcionario.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends funcionarioFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, funcionarioFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Funcionarios that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {funcionarioFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Funcionarios
   * const funcionarios = await prisma.funcionario.findMany()
   * 
   * // Get first 10 Funcionarios
   * const funcionarios = await prisma.funcionario.findMany({ take: 10 })
   * 
   * // Only select the `matricula`
   * const funcionarioWithMatriculaOnly = await prisma.funcionario.findMany({ select: { matricula: true } })
   * 
   */
  findMany<T extends funcionarioFindManyArgs>(args?: Prisma.SelectSubset<T, funcionarioFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Funcionario.
   * @param {funcionarioCreateArgs} args - Arguments to create a Funcionario.
   * @example
   * // Create one Funcionario
   * const Funcionario = await prisma.funcionario.create({
   *   data: {
   *     // ... data to create a Funcionario
   *   }
   * })
   * 
   */
  create<T extends funcionarioCreateArgs>(args: Prisma.SelectSubset<T, funcionarioCreateArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Funcionarios.
   * @param {funcionarioCreateManyArgs} args - Arguments to create many Funcionarios.
   * @example
   * // Create many Funcionarios
   * const funcionario = await prisma.funcionario.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends funcionarioCreateManyArgs>(args?: Prisma.SelectSubset<T, funcionarioCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Funcionarios and returns the data saved in the database.
   * @param {funcionarioCreateManyAndReturnArgs} args - Arguments to create many Funcionarios.
   * @example
   * // Create many Funcionarios
   * const funcionario = await prisma.funcionario.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Funcionarios and only return the `matricula`
   * const funcionarioWithMatriculaOnly = await prisma.funcionario.createManyAndReturn({
   *   select: { matricula: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends funcionarioCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, funcionarioCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Funcionario.
   * @param {funcionarioDeleteArgs} args - Arguments to delete one Funcionario.
   * @example
   * // Delete one Funcionario
   * const Funcionario = await prisma.funcionario.delete({
   *   where: {
   *     // ... filter to delete one Funcionario
   *   }
   * })
   * 
   */
  delete<T extends funcionarioDeleteArgs>(args: Prisma.SelectSubset<T, funcionarioDeleteArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Funcionario.
   * @param {funcionarioUpdateArgs} args - Arguments to update one Funcionario.
   * @example
   * // Update one Funcionario
   * const funcionario = await prisma.funcionario.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends funcionarioUpdateArgs>(args: Prisma.SelectSubset<T, funcionarioUpdateArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Funcionarios.
   * @param {funcionarioDeleteManyArgs} args - Arguments to filter Funcionarios to delete.
   * @example
   * // Delete a few Funcionarios
   * const { count } = await prisma.funcionario.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends funcionarioDeleteManyArgs>(args?: Prisma.SelectSubset<T, funcionarioDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Funcionarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {funcionarioUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Funcionarios
   * const funcionario = await prisma.funcionario.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends funcionarioUpdateManyArgs>(args: Prisma.SelectSubset<T, funcionarioUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Funcionarios and returns the data updated in the database.
   * @param {funcionarioUpdateManyAndReturnArgs} args - Arguments to update many Funcionarios.
   * @example
   * // Update many Funcionarios
   * const funcionario = await prisma.funcionario.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Funcionarios and only return the `matricula`
   * const funcionarioWithMatriculaOnly = await prisma.funcionario.updateManyAndReturn({
   *   select: { matricula: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends funcionarioUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, funcionarioUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Funcionario.
   * @param {funcionarioUpsertArgs} args - Arguments to update or create a Funcionario.
   * @example
   * // Update or create a Funcionario
   * const funcionario = await prisma.funcionario.upsert({
   *   create: {
   *     // ... data to create a Funcionario
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Funcionario we want to update
   *   }
   * })
   */
  upsert<T extends funcionarioUpsertArgs>(args: Prisma.SelectSubset<T, funcionarioUpsertArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Funcionarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {funcionarioCountArgs} args - Arguments to filter Funcionarios to count.
   * @example
   * // Count the number of Funcionarios
   * const count = await prisma.funcionario.count({
   *   where: {
   *     // ... the filter for the Funcionarios we want to count
   *   }
   * })
  **/
  count<T extends funcionarioCountArgs>(
    args?: Prisma.Subset<T, funcionarioCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FuncionarioCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Funcionario.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FuncionarioAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FuncionarioAggregateArgs>(args: Prisma.Subset<T, FuncionarioAggregateArgs>): Prisma.PrismaPromise<GetFuncionarioAggregateType<T>>

  /**
   * Group by Funcionario.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {funcionarioGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends funcionarioGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: funcionarioGroupByArgs['orderBy'] }
      : { orderBy?: funcionarioGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, funcionarioGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFuncionarioGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the funcionario model
 */
readonly fields: funcionarioFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for funcionario.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__funcionarioClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  funcionario_grupos<T extends Prisma.funcionario$funcionario_gruposArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.funcionario$funcionario_gruposArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$funcionario_grupoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  user_apps<T extends Prisma.funcionario$user_appsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.funcionario$user_appsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the funcionario model
 */
export interface funcionarioFieldRefs {
  readonly matricula: Prisma.FieldRef<"funcionario", 'String'>
  readonly nome: Prisma.FieldRef<"funcionario", 'String'>
  readonly username: Prisma.FieldRef<"funcionario", 'String'>
  readonly senha: Prisma.FieldRef<"funcionario", 'String'>
  readonly email: Prisma.FieldRef<"funcionario", 'String'>
}
    

// Custom InputTypes
/**
 * funcionario findUnique
 */
export type funcionarioFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * Filter, which funcionario to fetch.
   */
  where: Prisma.funcionarioWhereUniqueInput
}

/**
 * funcionario findUniqueOrThrow
 */
export type funcionarioFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * Filter, which funcionario to fetch.
   */
  where: Prisma.funcionarioWhereUniqueInput
}

/**
 * funcionario findFirst
 */
export type funcionarioFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * Filter, which funcionario to fetch.
   */
  where?: Prisma.funcionarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of funcionarios to fetch.
   */
  orderBy?: Prisma.funcionarioOrderByWithRelationInput | Prisma.funcionarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for funcionarios.
   */
  cursor?: Prisma.funcionarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` funcionarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` funcionarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of funcionarios.
   */
  distinct?: Prisma.FuncionarioScalarFieldEnum | Prisma.FuncionarioScalarFieldEnum[]
}

/**
 * funcionario findFirstOrThrow
 */
export type funcionarioFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * Filter, which funcionario to fetch.
   */
  where?: Prisma.funcionarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of funcionarios to fetch.
   */
  orderBy?: Prisma.funcionarioOrderByWithRelationInput | Prisma.funcionarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for funcionarios.
   */
  cursor?: Prisma.funcionarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` funcionarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` funcionarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of funcionarios.
   */
  distinct?: Prisma.FuncionarioScalarFieldEnum | Prisma.FuncionarioScalarFieldEnum[]
}

/**
 * funcionario findMany
 */
export type funcionarioFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * Filter, which funcionarios to fetch.
   */
  where?: Prisma.funcionarioWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of funcionarios to fetch.
   */
  orderBy?: Prisma.funcionarioOrderByWithRelationInput | Prisma.funcionarioOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing funcionarios.
   */
  cursor?: Prisma.funcionarioWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` funcionarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` funcionarios.
   */
  skip?: number
  distinct?: Prisma.FuncionarioScalarFieldEnum | Prisma.FuncionarioScalarFieldEnum[]
}

/**
 * funcionario create
 */
export type funcionarioCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * The data needed to create a funcionario.
   */
  data: Prisma.XOR<Prisma.funcionarioCreateInput, Prisma.funcionarioUncheckedCreateInput>
}

/**
 * funcionario createMany
 */
export type funcionarioCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many funcionarios.
   */
  data: Prisma.funcionarioCreateManyInput | Prisma.funcionarioCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * funcionario createManyAndReturn
 */
export type funcionarioCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * The data used to create many funcionarios.
   */
  data: Prisma.funcionarioCreateManyInput | Prisma.funcionarioCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * funcionario update
 */
export type funcionarioUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * The data needed to update a funcionario.
   */
  data: Prisma.XOR<Prisma.funcionarioUpdateInput, Prisma.funcionarioUncheckedUpdateInput>
  /**
   * Choose, which funcionario to update.
   */
  where: Prisma.funcionarioWhereUniqueInput
}

/**
 * funcionario updateMany
 */
export type funcionarioUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update funcionarios.
   */
  data: Prisma.XOR<Prisma.funcionarioUpdateManyMutationInput, Prisma.funcionarioUncheckedUpdateManyInput>
  /**
   * Filter which funcionarios to update
   */
  where?: Prisma.funcionarioWhereInput
  /**
   * Limit how many funcionarios to update.
   */
  limit?: number
}

/**
 * funcionario updateManyAndReturn
 */
export type funcionarioUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * The data used to update funcionarios.
   */
  data: Prisma.XOR<Prisma.funcionarioUpdateManyMutationInput, Prisma.funcionarioUncheckedUpdateManyInput>
  /**
   * Filter which funcionarios to update
   */
  where?: Prisma.funcionarioWhereInput
  /**
   * Limit how many funcionarios to update.
   */
  limit?: number
}

/**
 * funcionario upsert
 */
export type funcionarioUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * The filter to search for the funcionario to update in case it exists.
   */
  where: Prisma.funcionarioWhereUniqueInput
  /**
   * In case the funcionario found by the `where` argument doesn't exist, create a new funcionario with this data.
   */
  create: Prisma.XOR<Prisma.funcionarioCreateInput, Prisma.funcionarioUncheckedCreateInput>
  /**
   * In case the funcionario was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.funcionarioUpdateInput, Prisma.funcionarioUncheckedUpdateInput>
}

/**
 * funcionario delete
 */
export type funcionarioDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  /**
   * Filter which funcionario to delete.
   */
  where: Prisma.funcionarioWhereUniqueInput
}

/**
 * funcionario deleteMany
 */
export type funcionarioDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which funcionarios to delete
   */
  where?: Prisma.funcionarioWhereInput
  /**
   * Limit how many funcionarios to delete.
   */
  limit?: number
}

/**
 * funcionario.funcionario_grupos
 */
export type funcionario$funcionario_gruposArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario_grupo
   */
  select?: Prisma.funcionario_grupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario_grupo
   */
  omit?: Prisma.funcionario_grupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionario_grupoInclude<ExtArgs> | null
  where?: Prisma.funcionario_grupoWhereInput
  orderBy?: Prisma.funcionario_grupoOrderByWithRelationInput | Prisma.funcionario_grupoOrderByWithRelationInput[]
  cursor?: Prisma.funcionario_grupoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Funcionario_grupoScalarFieldEnum | Prisma.Funcionario_grupoScalarFieldEnum[]
}

/**
 * funcionario.user_apps
 */
export type funcionario$user_appsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  where?: Prisma.user_appWhereInput
  orderBy?: Prisma.user_appOrderByWithRelationInput | Prisma.user_appOrderByWithRelationInput[]
  cursor?: Prisma.user_appWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.User_appScalarFieldEnum | Prisma.User_appScalarFieldEnum[]
}

/**
 * funcionario without action
 */
export type funcionarioDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
}
