
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `time` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model time
 * 
 */
export type timeModel = runtime.Types.Result.DefaultSelection<Prisma.$timePayload>

export type AggregateTime = {
  _count: TimeCountAggregateOutputType | null
  _avg: TimeAvgAggregateOutputType | null
  _sum: TimeSumAggregateOutputType | null
  _min: TimeMinAggregateOutputType | null
  _max: TimeMaxAggregateOutputType | null
}

export type TimeAvgAggregateOutputType = {
  id_time: number | null
  id_grupo: number | null
}

export type TimeSumAggregateOutputType = {
  id_time: number | null
  id_grupo: number | null
}

export type TimeMinAggregateOutputType = {
  id_time: number | null
  nome: string | null
  id_grupo: number | null
  pdl: string | null
}

export type TimeMaxAggregateOutputType = {
  id_time: number | null
  nome: string | null
  id_grupo: number | null
  pdl: string | null
}

export type TimeCountAggregateOutputType = {
  id_time: number
  nome: number
  id_grupo: number
  pdl: number
  _all: number
}


export type TimeAvgAggregateInputType = {
  id_time?: true
  id_grupo?: true
}

export type TimeSumAggregateInputType = {
  id_time?: true
  id_grupo?: true
}

export type TimeMinAggregateInputType = {
  id_time?: true
  nome?: true
  id_grupo?: true
  pdl?: true
}

export type TimeMaxAggregateInputType = {
  id_time?: true
  nome?: true
  id_grupo?: true
  pdl?: true
}

export type TimeCountAggregateInputType = {
  id_time?: true
  nome?: true
  id_grupo?: true
  pdl?: true
  _all?: true
}

export type TimeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which time to aggregate.
   */
  where?: Prisma.timeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of times to fetch.
   */
  orderBy?: Prisma.timeOrderByWithRelationInput | Prisma.timeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.timeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` times from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` times.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned times
  **/
  _count?: true | TimeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TimeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TimeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TimeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TimeMaxAggregateInputType
}

export type GetTimeAggregateType<T extends TimeAggregateArgs> = {
      [P in keyof T & keyof AggregateTime]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTime[P]>
    : Prisma.GetScalarType<T[P], AggregateTime[P]>
}




export type timeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.timeWhereInput
  orderBy?: Prisma.timeOrderByWithAggregationInput | Prisma.timeOrderByWithAggregationInput[]
  by: Prisma.TimeScalarFieldEnum[] | Prisma.TimeScalarFieldEnum
  having?: Prisma.timeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TimeCountAggregateInputType | true
  _avg?: TimeAvgAggregateInputType
  _sum?: TimeSumAggregateInputType
  _min?: TimeMinAggregateInputType
  _max?: TimeMaxAggregateInputType
}

export type TimeGroupByOutputType = {
  id_time: number
  nome: string
  id_grupo: number | null
  pdl: string | null
  _count: TimeCountAggregateOutputType | null
  _avg: TimeAvgAggregateOutputType | null
  _sum: TimeSumAggregateOutputType | null
  _min: TimeMinAggregateOutputType | null
  _max: TimeMaxAggregateOutputType | null
}

type GetTimeGroupByPayload<T extends timeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TimeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TimeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TimeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TimeGroupByOutputType[P]>
      }
    >
  >



export type timeWhereInput = {
  AND?: Prisma.timeWhereInput | Prisma.timeWhereInput[]
  OR?: Prisma.timeWhereInput[]
  NOT?: Prisma.timeWhereInput | Prisma.timeWhereInput[]
  id_time?: Prisma.IntFilter<"time"> | number
  nome?: Prisma.StringFilter<"time"> | string
  id_grupo?: Prisma.IntNullableFilter<"time"> | number | null
  pdl?: Prisma.StringNullableFilter<"time"> | string | null
  grupo?: Prisma.XOR<Prisma.GrupoNullableScalarRelationFilter, Prisma.grupoWhereInput> | null
  aplicacoes?: Prisma.AplicacaoListRelationFilter
}

export type timeOrderByWithRelationInput = {
  id_time?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  id_grupo?: Prisma.SortOrderInput | Prisma.SortOrder
  pdl?: Prisma.SortOrderInput | Prisma.SortOrder
  grupo?: Prisma.grupoOrderByWithRelationInput
  aplicacoes?: Prisma.aplicacaoOrderByRelationAggregateInput
}

export type timeWhereUniqueInput = Prisma.AtLeast<{
  id_time?: number
  AND?: Prisma.timeWhereInput | Prisma.timeWhereInput[]
  OR?: Prisma.timeWhereInput[]
  NOT?: Prisma.timeWhereInput | Prisma.timeWhereInput[]
  nome?: Prisma.StringFilter<"time"> | string
  id_grupo?: Prisma.IntNullableFilter<"time"> | number | null
  pdl?: Prisma.StringNullableFilter<"time"> | string | null
  grupo?: Prisma.XOR<Prisma.GrupoNullableScalarRelationFilter, Prisma.grupoWhereInput> | null
  aplicacoes?: Prisma.AplicacaoListRelationFilter
}, "id_time">

export type timeOrderByWithAggregationInput = {
  id_time?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  id_grupo?: Prisma.SortOrderInput | Prisma.SortOrder
  pdl?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.timeCountOrderByAggregateInput
  _avg?: Prisma.timeAvgOrderByAggregateInput
  _max?: Prisma.timeMaxOrderByAggregateInput
  _min?: Prisma.timeMinOrderByAggregateInput
  _sum?: Prisma.timeSumOrderByAggregateInput
}

export type timeScalarWhereWithAggregatesInput = {
  AND?: Prisma.timeScalarWhereWithAggregatesInput | Prisma.timeScalarWhereWithAggregatesInput[]
  OR?: Prisma.timeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.timeScalarWhereWithAggregatesInput | Prisma.timeScalarWhereWithAggregatesInput[]
  id_time?: Prisma.IntWithAggregatesFilter<"time"> | number
  nome?: Prisma.StringWithAggregatesFilter<"time"> | string
  id_grupo?: Prisma.IntNullableWithAggregatesFilter<"time"> | number | null
  pdl?: Prisma.StringNullableWithAggregatesFilter<"time"> | string | null
}

export type timeCreateInput = {
  nome: string
  pdl?: string | null
  grupo?: Prisma.grupoCreateNestedOneWithoutTimesInput
  aplicacoes?: Prisma.aplicacaoCreateNestedManyWithoutTimeInput
}

export type timeUncheckedCreateInput = {
  id_time?: number
  nome: string
  id_grupo?: number | null
  pdl?: string | null
  aplicacoes?: Prisma.aplicacaoUncheckedCreateNestedManyWithoutTimeInput
}

export type timeUpdateInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grupo?: Prisma.grupoUpdateOneWithoutTimesNestedInput
  aplicacoes?: Prisma.aplicacaoUpdateManyWithoutTimeNestedInput
}

export type timeUncheckedUpdateInput = {
  id_time?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  id_grupo?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aplicacoes?: Prisma.aplicacaoUncheckedUpdateManyWithoutTimeNestedInput
}

export type timeCreateManyInput = {
  id_time?: number
  nome: string
  id_grupo?: number | null
  pdl?: string | null
}

export type timeUpdateManyMutationInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type timeUncheckedUpdateManyInput = {
  id_time?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  id_grupo?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TimeListRelationFilter = {
  every?: Prisma.timeWhereInput
  some?: Prisma.timeWhereInput
  none?: Prisma.timeWhereInput
}

export type timeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type timeCountOrderByAggregateInput = {
  id_time?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  id_grupo?: Prisma.SortOrder
  pdl?: Prisma.SortOrder
}

export type timeAvgOrderByAggregateInput = {
  id_time?: Prisma.SortOrder
  id_grupo?: Prisma.SortOrder
}

export type timeMaxOrderByAggregateInput = {
  id_time?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  id_grupo?: Prisma.SortOrder
  pdl?: Prisma.SortOrder
}

export type timeMinOrderByAggregateInput = {
  id_time?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  id_grupo?: Prisma.SortOrder
  pdl?: Prisma.SortOrder
}

export type timeSumOrderByAggregateInput = {
  id_time?: Prisma.SortOrder
  id_grupo?: Prisma.SortOrder
}

export type TimeNullableScalarRelationFilter = {
  is?: Prisma.timeWhereInput | null
  isNot?: Prisma.timeWhereInput | null
}

export type timeCreateNestedManyWithoutGrupoInput = {
  create?: Prisma.XOR<Prisma.timeCreateWithoutGrupoInput, Prisma.timeUncheckedCreateWithoutGrupoInput> | Prisma.timeCreateWithoutGrupoInput[] | Prisma.timeUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.timeCreateOrConnectWithoutGrupoInput | Prisma.timeCreateOrConnectWithoutGrupoInput[]
  createMany?: Prisma.timeCreateManyGrupoInputEnvelope
  connect?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
}

export type timeUncheckedCreateNestedManyWithoutGrupoInput = {
  create?: Prisma.XOR<Prisma.timeCreateWithoutGrupoInput, Prisma.timeUncheckedCreateWithoutGrupoInput> | Prisma.timeCreateWithoutGrupoInput[] | Prisma.timeUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.timeCreateOrConnectWithoutGrupoInput | Prisma.timeCreateOrConnectWithoutGrupoInput[]
  createMany?: Prisma.timeCreateManyGrupoInputEnvelope
  connect?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
}

export type timeUpdateManyWithoutGrupoNestedInput = {
  create?: Prisma.XOR<Prisma.timeCreateWithoutGrupoInput, Prisma.timeUncheckedCreateWithoutGrupoInput> | Prisma.timeCreateWithoutGrupoInput[] | Prisma.timeUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.timeCreateOrConnectWithoutGrupoInput | Prisma.timeCreateOrConnectWithoutGrupoInput[]
  upsert?: Prisma.timeUpsertWithWhereUniqueWithoutGrupoInput | Prisma.timeUpsertWithWhereUniqueWithoutGrupoInput[]
  createMany?: Prisma.timeCreateManyGrupoInputEnvelope
  set?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
  disconnect?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
  delete?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
  connect?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
  update?: Prisma.timeUpdateWithWhereUniqueWithoutGrupoInput | Prisma.timeUpdateWithWhereUniqueWithoutGrupoInput[]
  updateMany?: Prisma.timeUpdateManyWithWhereWithoutGrupoInput | Prisma.timeUpdateManyWithWhereWithoutGrupoInput[]
  deleteMany?: Prisma.timeScalarWhereInput | Prisma.timeScalarWhereInput[]
}

export type timeUncheckedUpdateManyWithoutGrupoNestedInput = {
  create?: Prisma.XOR<Prisma.timeCreateWithoutGrupoInput, Prisma.timeUncheckedCreateWithoutGrupoInput> | Prisma.timeCreateWithoutGrupoInput[] | Prisma.timeUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.timeCreateOrConnectWithoutGrupoInput | Prisma.timeCreateOrConnectWithoutGrupoInput[]
  upsert?: Prisma.timeUpsertWithWhereUniqueWithoutGrupoInput | Prisma.timeUpsertWithWhereUniqueWithoutGrupoInput[]
  createMany?: Prisma.timeCreateManyGrupoInputEnvelope
  set?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
  disconnect?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
  delete?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
  connect?: Prisma.timeWhereUniqueInput | Prisma.timeWhereUniqueInput[]
  update?: Prisma.timeUpdateWithWhereUniqueWithoutGrupoInput | Prisma.timeUpdateWithWhereUniqueWithoutGrupoInput[]
  updateMany?: Prisma.timeUpdateManyWithWhereWithoutGrupoInput | Prisma.timeUpdateManyWithWhereWithoutGrupoInput[]
  deleteMany?: Prisma.timeScalarWhereInput | Prisma.timeScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type timeCreateNestedOneWithoutAplicacoesInput = {
  create?: Prisma.XOR<Prisma.timeCreateWithoutAplicacoesInput, Prisma.timeUncheckedCreateWithoutAplicacoesInput>
  connectOrCreate?: Prisma.timeCreateOrConnectWithoutAplicacoesInput
  connect?: Prisma.timeWhereUniqueInput
}

export type timeUpdateOneWithoutAplicacoesNestedInput = {
  create?: Prisma.XOR<Prisma.timeCreateWithoutAplicacoesInput, Prisma.timeUncheckedCreateWithoutAplicacoesInput>
  connectOrCreate?: Prisma.timeCreateOrConnectWithoutAplicacoesInput
  upsert?: Prisma.timeUpsertWithoutAplicacoesInput
  disconnect?: Prisma.timeWhereInput | boolean
  delete?: Prisma.timeWhereInput | boolean
  connect?: Prisma.timeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.timeUpdateToOneWithWhereWithoutAplicacoesInput, Prisma.timeUpdateWithoutAplicacoesInput>, Prisma.timeUncheckedUpdateWithoutAplicacoesInput>
}

export type timeCreateWithoutGrupoInput = {
  nome: string
  pdl?: string | null
  aplicacoes?: Prisma.aplicacaoCreateNestedManyWithoutTimeInput
}

export type timeUncheckedCreateWithoutGrupoInput = {
  id_time?: number
  nome: string
  pdl?: string | null
  aplicacoes?: Prisma.aplicacaoUncheckedCreateNestedManyWithoutTimeInput
}

export type timeCreateOrConnectWithoutGrupoInput = {
  where: Prisma.timeWhereUniqueInput
  create: Prisma.XOR<Prisma.timeCreateWithoutGrupoInput, Prisma.timeUncheckedCreateWithoutGrupoInput>
}

export type timeCreateManyGrupoInputEnvelope = {
  data: Prisma.timeCreateManyGrupoInput | Prisma.timeCreateManyGrupoInput[]
  skipDuplicates?: boolean
}

export type timeUpsertWithWhereUniqueWithoutGrupoInput = {
  where: Prisma.timeWhereUniqueInput
  update: Prisma.XOR<Prisma.timeUpdateWithoutGrupoInput, Prisma.timeUncheckedUpdateWithoutGrupoInput>
  create: Prisma.XOR<Prisma.timeCreateWithoutGrupoInput, Prisma.timeUncheckedCreateWithoutGrupoInput>
}

export type timeUpdateWithWhereUniqueWithoutGrupoInput = {
  where: Prisma.timeWhereUniqueInput
  data: Prisma.XOR<Prisma.timeUpdateWithoutGrupoInput, Prisma.timeUncheckedUpdateWithoutGrupoInput>
}

export type timeUpdateManyWithWhereWithoutGrupoInput = {
  where: Prisma.timeScalarWhereInput
  data: Prisma.XOR<Prisma.timeUpdateManyMutationInput, Prisma.timeUncheckedUpdateManyWithoutGrupoInput>
}

export type timeScalarWhereInput = {
  AND?: Prisma.timeScalarWhereInput | Prisma.timeScalarWhereInput[]
  OR?: Prisma.timeScalarWhereInput[]
  NOT?: Prisma.timeScalarWhereInput | Prisma.timeScalarWhereInput[]
  id_time?: Prisma.IntFilter<"time"> | number
  nome?: Prisma.StringFilter<"time"> | string
  id_grupo?: Prisma.IntNullableFilter<"time"> | number | null
  pdl?: Prisma.StringNullableFilter<"time"> | string | null
}

export type timeCreateWithoutAplicacoesInput = {
  nome: string
  pdl?: string | null
  grupo?: Prisma.grupoCreateNestedOneWithoutTimesInput
}

export type timeUncheckedCreateWithoutAplicacoesInput = {
  id_time?: number
  nome: string
  id_grupo?: number | null
  pdl?: string | null
}

export type timeCreateOrConnectWithoutAplicacoesInput = {
  where: Prisma.timeWhereUniqueInput
  create: Prisma.XOR<Prisma.timeCreateWithoutAplicacoesInput, Prisma.timeUncheckedCreateWithoutAplicacoesInput>
}

export type timeUpsertWithoutAplicacoesInput = {
  update: Prisma.XOR<Prisma.timeUpdateWithoutAplicacoesInput, Prisma.timeUncheckedUpdateWithoutAplicacoesInput>
  create: Prisma.XOR<Prisma.timeCreateWithoutAplicacoesInput, Prisma.timeUncheckedCreateWithoutAplicacoesInput>
  where?: Prisma.timeWhereInput
}

export type timeUpdateToOneWithWhereWithoutAplicacoesInput = {
  where?: Prisma.timeWhereInput
  data: Prisma.XOR<Prisma.timeUpdateWithoutAplicacoesInput, Prisma.timeUncheckedUpdateWithoutAplicacoesInput>
}

export type timeUpdateWithoutAplicacoesInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grupo?: Prisma.grupoUpdateOneWithoutTimesNestedInput
}

export type timeUncheckedUpdateWithoutAplicacoesInput = {
  id_time?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  id_grupo?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type timeCreateManyGrupoInput = {
  id_time?: number
  nome: string
  pdl?: string | null
}

export type timeUpdateWithoutGrupoInput = {
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aplicacoes?: Prisma.aplicacaoUpdateManyWithoutTimeNestedInput
}

export type timeUncheckedUpdateWithoutGrupoInput = {
  id_time?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aplicacoes?: Prisma.aplicacaoUncheckedUpdateManyWithoutTimeNestedInput
}

export type timeUncheckedUpdateManyWithoutGrupoInput = {
  id_time?: Prisma.IntFieldUpdateOperationsInput | number
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  pdl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type TimeCountOutputType
 */

export type TimeCountOutputType = {
  aplicacoes: number
}

export type TimeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  aplicacoes?: boolean | TimeCountOutputTypeCountAplicacoesArgs
}

/**
 * TimeCountOutputType without action
 */
export type TimeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeCountOutputType
   */
  select?: Prisma.TimeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TimeCountOutputType without action
 */
export type TimeCountOutputTypeCountAplicacoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.aplicacaoWhereInput
}


export type timeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_time?: boolean
  nome?: boolean
  id_grupo?: boolean
  pdl?: boolean
  grupo?: boolean | Prisma.time$grupoArgs<ExtArgs>
  aplicacoes?: boolean | Prisma.time$aplicacoesArgs<ExtArgs>
  _count?: boolean | Prisma.TimeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["time"]>

export type timeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_time?: boolean
  nome?: boolean
  id_grupo?: boolean
  pdl?: boolean
  grupo?: boolean | Prisma.time$grupoArgs<ExtArgs>
}, ExtArgs["result"]["time"]>

export type timeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_time?: boolean
  nome?: boolean
  id_grupo?: boolean
  pdl?: boolean
  grupo?: boolean | Prisma.time$grupoArgs<ExtArgs>
}, ExtArgs["result"]["time"]>

export type timeSelectScalar = {
  id_time?: boolean
  nome?: boolean
  id_grupo?: boolean
  pdl?: boolean
}

export type timeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id_time" | "nome" | "id_grupo" | "pdl", ExtArgs["result"]["time"]>
export type timeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.time$grupoArgs<ExtArgs>
  aplicacoes?: boolean | Prisma.time$aplicacoesArgs<ExtArgs>
  _count?: boolean | Prisma.TimeCountOutputTypeDefaultArgs<ExtArgs>
}
export type timeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.time$grupoArgs<ExtArgs>
}
export type timeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.time$grupoArgs<ExtArgs>
}

export type $timePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "time"
  objects: {
    grupo: Prisma.$grupoPayload<ExtArgs> | null
    aplicacoes: Prisma.$aplicacaoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id_time: number
    nome: string
    id_grupo: number | null
    pdl: string | null
  }, ExtArgs["result"]["time"]>
  composites: {}
}

export type timeGetPayload<S extends boolean | null | undefined | timeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$timePayload, S>

export type timeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<timeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TimeCountAggregateInputType | true
  }

export interface timeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['time'], meta: { name: 'time' } }
  /**
   * Find zero or one Time that matches the filter.
   * @param {timeFindUniqueArgs} args - Arguments to find a Time
   * @example
   * // Get one Time
   * const time = await prisma.time.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends timeFindUniqueArgs>(args: Prisma.SelectSubset<T, timeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__timeClient<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Time that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {timeFindUniqueOrThrowArgs} args - Arguments to find a Time
   * @example
   * // Get one Time
   * const time = await prisma.time.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends timeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, timeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__timeClient<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Time that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {timeFindFirstArgs} args - Arguments to find a Time
   * @example
   * // Get one Time
   * const time = await prisma.time.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends timeFindFirstArgs>(args?: Prisma.SelectSubset<T, timeFindFirstArgs<ExtArgs>>): Prisma.Prisma__timeClient<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Time that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {timeFindFirstOrThrowArgs} args - Arguments to find a Time
   * @example
   * // Get one Time
   * const time = await prisma.time.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends timeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, timeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__timeClient<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Times that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {timeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Times
   * const times = await prisma.time.findMany()
   * 
   * // Get first 10 Times
   * const times = await prisma.time.findMany({ take: 10 })
   * 
   * // Only select the `id_time`
   * const timeWithId_timeOnly = await prisma.time.findMany({ select: { id_time: true } })
   * 
   */
  findMany<T extends timeFindManyArgs>(args?: Prisma.SelectSubset<T, timeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Time.
   * @param {timeCreateArgs} args - Arguments to create a Time.
   * @example
   * // Create one Time
   * const Time = await prisma.time.create({
   *   data: {
   *     // ... data to create a Time
   *   }
   * })
   * 
   */
  create<T extends timeCreateArgs>(args: Prisma.SelectSubset<T, timeCreateArgs<ExtArgs>>): Prisma.Prisma__timeClient<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Times.
   * @param {timeCreateManyArgs} args - Arguments to create many Times.
   * @example
   * // Create many Times
   * const time = await prisma.time.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends timeCreateManyArgs>(args?: Prisma.SelectSubset<T, timeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Times and returns the data saved in the database.
   * @param {timeCreateManyAndReturnArgs} args - Arguments to create many Times.
   * @example
   * // Create many Times
   * const time = await prisma.time.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Times and only return the `id_time`
   * const timeWithId_timeOnly = await prisma.time.createManyAndReturn({
   *   select: { id_time: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends timeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, timeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Time.
   * @param {timeDeleteArgs} args - Arguments to delete one Time.
   * @example
   * // Delete one Time
   * const Time = await prisma.time.delete({
   *   where: {
   *     // ... filter to delete one Time
   *   }
   * })
   * 
   */
  delete<T extends timeDeleteArgs>(args: Prisma.SelectSubset<T, timeDeleteArgs<ExtArgs>>): Prisma.Prisma__timeClient<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Time.
   * @param {timeUpdateArgs} args - Arguments to update one Time.
   * @example
   * // Update one Time
   * const time = await prisma.time.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends timeUpdateArgs>(args: Prisma.SelectSubset<T, timeUpdateArgs<ExtArgs>>): Prisma.Prisma__timeClient<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Times.
   * @param {timeDeleteManyArgs} args - Arguments to filter Times to delete.
   * @example
   * // Delete a few Times
   * const { count } = await prisma.time.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends timeDeleteManyArgs>(args?: Prisma.SelectSubset<T, timeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Times.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {timeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Times
   * const time = await prisma.time.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends timeUpdateManyArgs>(args: Prisma.SelectSubset<T, timeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Times and returns the data updated in the database.
   * @param {timeUpdateManyAndReturnArgs} args - Arguments to update many Times.
   * @example
   * // Update many Times
   * const time = await prisma.time.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Times and only return the `id_time`
   * const timeWithId_timeOnly = await prisma.time.updateManyAndReturn({
   *   select: { id_time: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends timeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, timeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Time.
   * @param {timeUpsertArgs} args - Arguments to update or create a Time.
   * @example
   * // Update or create a Time
   * const time = await prisma.time.upsert({
   *   create: {
   *     // ... data to create a Time
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Time we want to update
   *   }
   * })
   */
  upsert<T extends timeUpsertArgs>(args: Prisma.SelectSubset<T, timeUpsertArgs<ExtArgs>>): Prisma.Prisma__timeClient<runtime.Types.Result.GetResult<Prisma.$timePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Times.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {timeCountArgs} args - Arguments to filter Times to count.
   * @example
   * // Count the number of Times
   * const count = await prisma.time.count({
   *   where: {
   *     // ... the filter for the Times we want to count
   *   }
   * })
  **/
  count<T extends timeCountArgs>(
    args?: Prisma.Subset<T, timeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TimeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Time.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TimeAggregateArgs>(args: Prisma.Subset<T, TimeAggregateArgs>): Prisma.PrismaPromise<GetTimeAggregateType<T>>

  /**
   * Group by Time.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {timeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends timeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: timeGroupByArgs['orderBy'] }
      : { orderBy?: timeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, timeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTimeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the time model
 */
readonly fields: timeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for time.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__timeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  grupo<T extends Prisma.time$grupoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.time$grupoArgs<ExtArgs>>): Prisma.Prisma__grupoClient<runtime.Types.Result.GetResult<Prisma.$grupoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  aplicacoes<T extends Prisma.time$aplicacoesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.time$aplicacoesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$aplicacaoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the time model
 */
export interface timeFieldRefs {
  readonly id_time: Prisma.FieldRef<"time", 'Int'>
  readonly nome: Prisma.FieldRef<"time", 'String'>
  readonly id_grupo: Prisma.FieldRef<"time", 'Int'>
  readonly pdl: Prisma.FieldRef<"time", 'String'>
}
    

// Custom InputTypes
/**
 * time findUnique
 */
export type timeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * Filter, which time to fetch.
   */
  where: Prisma.timeWhereUniqueInput
}

/**
 * time findUniqueOrThrow
 */
export type timeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * Filter, which time to fetch.
   */
  where: Prisma.timeWhereUniqueInput
}

/**
 * time findFirst
 */
export type timeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * Filter, which time to fetch.
   */
  where?: Prisma.timeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of times to fetch.
   */
  orderBy?: Prisma.timeOrderByWithRelationInput | Prisma.timeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for times.
   */
  cursor?: Prisma.timeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` times from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` times.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of times.
   */
  distinct?: Prisma.TimeScalarFieldEnum | Prisma.TimeScalarFieldEnum[]
}

/**
 * time findFirstOrThrow
 */
export type timeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * Filter, which time to fetch.
   */
  where?: Prisma.timeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of times to fetch.
   */
  orderBy?: Prisma.timeOrderByWithRelationInput | Prisma.timeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for times.
   */
  cursor?: Prisma.timeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` times from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` times.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of times.
   */
  distinct?: Prisma.TimeScalarFieldEnum | Prisma.TimeScalarFieldEnum[]
}

/**
 * time findMany
 */
export type timeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * Filter, which times to fetch.
   */
  where?: Prisma.timeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of times to fetch.
   */
  orderBy?: Prisma.timeOrderByWithRelationInput | Prisma.timeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing times.
   */
  cursor?: Prisma.timeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` times from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` times.
   */
  skip?: number
  distinct?: Prisma.TimeScalarFieldEnum | Prisma.TimeScalarFieldEnum[]
}

/**
 * time create
 */
export type timeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * The data needed to create a time.
   */
  data: Prisma.XOR<Prisma.timeCreateInput, Prisma.timeUncheckedCreateInput>
}

/**
 * time createMany
 */
export type timeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many times.
   */
  data: Prisma.timeCreateManyInput | Prisma.timeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * time createManyAndReturn
 */
export type timeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * The data used to create many times.
   */
  data: Prisma.timeCreateManyInput | Prisma.timeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * time update
 */
export type timeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * The data needed to update a time.
   */
  data: Prisma.XOR<Prisma.timeUpdateInput, Prisma.timeUncheckedUpdateInput>
  /**
   * Choose, which time to update.
   */
  where: Prisma.timeWhereUniqueInput
}

/**
 * time updateMany
 */
export type timeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update times.
   */
  data: Prisma.XOR<Prisma.timeUpdateManyMutationInput, Prisma.timeUncheckedUpdateManyInput>
  /**
   * Filter which times to update
   */
  where?: Prisma.timeWhereInput
  /**
   * Limit how many times to update.
   */
  limit?: number
}

/**
 * time updateManyAndReturn
 */
export type timeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * The data used to update times.
   */
  data: Prisma.XOR<Prisma.timeUpdateManyMutationInput, Prisma.timeUncheckedUpdateManyInput>
  /**
   * Filter which times to update
   */
  where?: Prisma.timeWhereInput
  /**
   * Limit how many times to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * time upsert
 */
export type timeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * The filter to search for the time to update in case it exists.
   */
  where: Prisma.timeWhereUniqueInput
  /**
   * In case the time found by the `where` argument doesn't exist, create a new time with this data.
   */
  create: Prisma.XOR<Prisma.timeCreateInput, Prisma.timeUncheckedCreateInput>
  /**
   * In case the time was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.timeUpdateInput, Prisma.timeUncheckedUpdateInput>
}

/**
 * time delete
 */
export type timeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
  /**
   * Filter which time to delete.
   */
  where: Prisma.timeWhereUniqueInput
}

/**
 * time deleteMany
 */
export type timeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which times to delete
   */
  where?: Prisma.timeWhereInput
  /**
   * Limit how many times to delete.
   */
  limit?: number
}

/**
 * time.grupo
 */
export type time$grupoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the grupo
   */
  select?: Prisma.grupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the grupo
   */
  omit?: Prisma.grupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.grupoInclude<ExtArgs> | null
  where?: Prisma.grupoWhereInput
}

/**
 * time.aplicacoes
 */
export type time$aplicacoesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the aplicacao
   */
  select?: Prisma.aplicacaoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the aplicacao
   */
  omit?: Prisma.aplicacaoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.aplicacaoInclude<ExtArgs> | null
  where?: Prisma.aplicacaoWhereInput
  orderBy?: Prisma.aplicacaoOrderByWithRelationInput | Prisma.aplicacaoOrderByWithRelationInput[]
  cursor?: Prisma.aplicacaoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AplicacaoScalarFieldEnum | Prisma.AplicacaoScalarFieldEnum[]
}

/**
 * time without action
 */
export type timeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the time
   */
  select?: Prisma.timeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the time
   */
  omit?: Prisma.timeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.timeInclude<ExtArgs> | null
}
