
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `user_app` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model user_app
 * 
 */
export type user_appModel = runtime.Types.Result.DefaultSelection<Prisma.$user_appPayload>

export type AggregateUser_app = {
  _count: User_appCountAggregateOutputType | null
  _avg: User_appAvgAggregateOutputType | null
  _sum: User_appSumAggregateOutputType | null
  _min: User_appMinAggregateOutputType | null
  _max: User_appMaxAggregateOutputType | null
}

export type User_appAvgAggregateOutputType = {
  id_user_app: number | null
}

export type User_appSumAggregateOutputType = {
  id_user_app: number | null
}

export type User_appMinAggregateOutputType = {
  id_user_app: number | null
  username: string | null
  senha: string | null
  matricula_funcionario: string | null
}

export type User_appMaxAggregateOutputType = {
  id_user_app: number | null
  username: string | null
  senha: string | null
  matricula_funcionario: string | null
}

export type User_appCountAggregateOutputType = {
  id_user_app: number
  username: number
  senha: number
  matricula_funcionario: number
  _all: number
}


export type User_appAvgAggregateInputType = {
  id_user_app?: true
}

export type User_appSumAggregateInputType = {
  id_user_app?: true
}

export type User_appMinAggregateInputType = {
  id_user_app?: true
  username?: true
  senha?: true
  matricula_funcionario?: true
}

export type User_appMaxAggregateInputType = {
  id_user_app?: true
  username?: true
  senha?: true
  matricula_funcionario?: true
}

export type User_appCountAggregateInputType = {
  id_user_app?: true
  username?: true
  senha?: true
  matricula_funcionario?: true
  _all?: true
}

export type User_appAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_app to aggregate.
   */
  where?: Prisma.user_appWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_apps to fetch.
   */
  orderBy?: Prisma.user_appOrderByWithRelationInput | Prisma.user_appOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.user_appWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_apps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_apps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned user_apps
  **/
  _count?: true | User_appCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: User_appAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: User_appSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: User_appMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: User_appMaxAggregateInputType
}

export type GetUser_appAggregateType<T extends User_appAggregateArgs> = {
      [P in keyof T & keyof AggregateUser_app]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser_app[P]>
    : Prisma.GetScalarType<T[P], AggregateUser_app[P]>
}




export type user_appGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.user_appWhereInput
  orderBy?: Prisma.user_appOrderByWithAggregationInput | Prisma.user_appOrderByWithAggregationInput[]
  by: Prisma.User_appScalarFieldEnum[] | Prisma.User_appScalarFieldEnum
  having?: Prisma.user_appScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: User_appCountAggregateInputType | true
  _avg?: User_appAvgAggregateInputType
  _sum?: User_appSumAggregateInputType
  _min?: User_appMinAggregateInputType
  _max?: User_appMaxAggregateInputType
}

export type User_appGroupByOutputType = {
  id_user_app: number
  username: string
  senha: string
  matricula_funcionario: string | null
  _count: User_appCountAggregateOutputType | null
  _avg: User_appAvgAggregateOutputType | null
  _sum: User_appSumAggregateOutputType | null
  _min: User_appMinAggregateOutputType | null
  _max: User_appMaxAggregateOutputType | null
}

type GetUser_appGroupByPayload<T extends user_appGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<User_appGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof User_appGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], User_appGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], User_appGroupByOutputType[P]>
      }
    >
  >



export type user_appWhereInput = {
  AND?: Prisma.user_appWhereInput | Prisma.user_appWhereInput[]
  OR?: Prisma.user_appWhereInput[]
  NOT?: Prisma.user_appWhereInput | Prisma.user_appWhereInput[]
  id_user_app?: Prisma.IntFilter<"user_app"> | number
  username?: Prisma.StringFilter<"user_app"> | string
  senha?: Prisma.StringFilter<"user_app"> | string
  matricula_funcionario?: Prisma.StringNullableFilter<"user_app"> | string | null
  funcionario?: Prisma.XOR<Prisma.FuncionarioNullableScalarRelationFilter, Prisma.funcionarioWhereInput> | null
  aplicacao_user_app?: Prisma.Aplicacao_user_appListRelationFilter
}

export type user_appOrderByWithRelationInput = {
  id_user_app?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  matricula_funcionario?: Prisma.SortOrderInput | Prisma.SortOrder
  funcionario?: Prisma.funcionarioOrderByWithRelationInput
  aplicacao_user_app?: Prisma.aplicacao_user_appOrderByRelationAggregateInput
}

export type user_appWhereUniqueInput = Prisma.AtLeast<{
  id_user_app?: number
  AND?: Prisma.user_appWhereInput | Prisma.user_appWhereInput[]
  OR?: Prisma.user_appWhereInput[]
  NOT?: Prisma.user_appWhereInput | Prisma.user_appWhereInput[]
  username?: Prisma.StringFilter<"user_app"> | string
  senha?: Prisma.StringFilter<"user_app"> | string
  matricula_funcionario?: Prisma.StringNullableFilter<"user_app"> | string | null
  funcionario?: Prisma.XOR<Prisma.FuncionarioNullableScalarRelationFilter, Prisma.funcionarioWhereInput> | null
  aplicacao_user_app?: Prisma.Aplicacao_user_appListRelationFilter
}, "id_user_app">

export type user_appOrderByWithAggregationInput = {
  id_user_app?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  matricula_funcionario?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.user_appCountOrderByAggregateInput
  _avg?: Prisma.user_appAvgOrderByAggregateInput
  _max?: Prisma.user_appMaxOrderByAggregateInput
  _min?: Prisma.user_appMinOrderByAggregateInput
  _sum?: Prisma.user_appSumOrderByAggregateInput
}

export type user_appScalarWhereWithAggregatesInput = {
  AND?: Prisma.user_appScalarWhereWithAggregatesInput | Prisma.user_appScalarWhereWithAggregatesInput[]
  OR?: Prisma.user_appScalarWhereWithAggregatesInput[]
  NOT?: Prisma.user_appScalarWhereWithAggregatesInput | Prisma.user_appScalarWhereWithAggregatesInput[]
  id_user_app?: Prisma.IntWithAggregatesFilter<"user_app"> | number
  username?: Prisma.StringWithAggregatesFilter<"user_app"> | string
  senha?: Prisma.StringWithAggregatesFilter<"user_app"> | string
  matricula_funcionario?: Prisma.StringNullableWithAggregatesFilter<"user_app"> | string | null
}

export type user_appCreateInput = {
  username: string
  senha: string
  funcionario?: Prisma.funcionarioCreateNestedOneWithoutUser_appsInput
  aplicacao_user_app?: Prisma.aplicacao_user_appCreateNestedManyWithoutUser_appInput
}

export type user_appUncheckedCreateInput = {
  id_user_app?: number
  username: string
  senha: string
  matricula_funcionario?: string | null
  aplicacao_user_app?: Prisma.aplicacao_user_appUncheckedCreateNestedManyWithoutUser_appInput
}

export type user_appUpdateInput = {
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  funcionario?: Prisma.funcionarioUpdateOneWithoutUser_appsNestedInput
  aplicacao_user_app?: Prisma.aplicacao_user_appUpdateManyWithoutUser_appNestedInput
}

export type user_appUncheckedUpdateInput = {
  id_user_app?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  matricula_funcionario?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aplicacao_user_app?: Prisma.aplicacao_user_appUncheckedUpdateManyWithoutUser_appNestedInput
}

export type user_appCreateManyInput = {
  id_user_app?: number
  username: string
  senha: string
  matricula_funcionario?: string | null
}

export type user_appUpdateManyMutationInput = {
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
}

export type user_appUncheckedUpdateManyInput = {
  id_user_app?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  matricula_funcionario?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type User_appListRelationFilter = {
  every?: Prisma.user_appWhereInput
  some?: Prisma.user_appWhereInput
  none?: Prisma.user_appWhereInput
}

export type user_appOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type user_appCountOrderByAggregateInput = {
  id_user_app?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  matricula_funcionario?: Prisma.SortOrder
}

export type user_appAvgOrderByAggregateInput = {
  id_user_app?: Prisma.SortOrder
}

export type user_appMaxOrderByAggregateInput = {
  id_user_app?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  matricula_funcionario?: Prisma.SortOrder
}

export type user_appMinOrderByAggregateInput = {
  id_user_app?: Prisma.SortOrder
  username?: Prisma.SortOrder
  senha?: Prisma.SortOrder
  matricula_funcionario?: Prisma.SortOrder
}

export type user_appSumOrderByAggregateInput = {
  id_user_app?: Prisma.SortOrder
}

export type User_appScalarRelationFilter = {
  is?: Prisma.user_appWhereInput
  isNot?: Prisma.user_appWhereInput
}

export type user_appCreateNestedManyWithoutFuncionarioInput = {
  create?: Prisma.XOR<Prisma.user_appCreateWithoutFuncionarioInput, Prisma.user_appUncheckedCreateWithoutFuncionarioInput> | Prisma.user_appCreateWithoutFuncionarioInput[] | Prisma.user_appUncheckedCreateWithoutFuncionarioInput[]
  connectOrCreate?: Prisma.user_appCreateOrConnectWithoutFuncionarioInput | Prisma.user_appCreateOrConnectWithoutFuncionarioInput[]
  createMany?: Prisma.user_appCreateManyFuncionarioInputEnvelope
  connect?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
}

export type user_appUncheckedCreateNestedManyWithoutFuncionarioInput = {
  create?: Prisma.XOR<Prisma.user_appCreateWithoutFuncionarioInput, Prisma.user_appUncheckedCreateWithoutFuncionarioInput> | Prisma.user_appCreateWithoutFuncionarioInput[] | Prisma.user_appUncheckedCreateWithoutFuncionarioInput[]
  connectOrCreate?: Prisma.user_appCreateOrConnectWithoutFuncionarioInput | Prisma.user_appCreateOrConnectWithoutFuncionarioInput[]
  createMany?: Prisma.user_appCreateManyFuncionarioInputEnvelope
  connect?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
}

export type user_appUpdateManyWithoutFuncionarioNestedInput = {
  create?: Prisma.XOR<Prisma.user_appCreateWithoutFuncionarioInput, Prisma.user_appUncheckedCreateWithoutFuncionarioInput> | Prisma.user_appCreateWithoutFuncionarioInput[] | Prisma.user_appUncheckedCreateWithoutFuncionarioInput[]
  connectOrCreate?: Prisma.user_appCreateOrConnectWithoutFuncionarioInput | Prisma.user_appCreateOrConnectWithoutFuncionarioInput[]
  upsert?: Prisma.user_appUpsertWithWhereUniqueWithoutFuncionarioInput | Prisma.user_appUpsertWithWhereUniqueWithoutFuncionarioInput[]
  createMany?: Prisma.user_appCreateManyFuncionarioInputEnvelope
  set?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
  disconnect?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
  delete?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
  connect?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
  update?: Prisma.user_appUpdateWithWhereUniqueWithoutFuncionarioInput | Prisma.user_appUpdateWithWhereUniqueWithoutFuncionarioInput[]
  updateMany?: Prisma.user_appUpdateManyWithWhereWithoutFuncionarioInput | Prisma.user_appUpdateManyWithWhereWithoutFuncionarioInput[]
  deleteMany?: Prisma.user_appScalarWhereInput | Prisma.user_appScalarWhereInput[]
}

export type user_appUncheckedUpdateManyWithoutFuncionarioNestedInput = {
  create?: Prisma.XOR<Prisma.user_appCreateWithoutFuncionarioInput, Prisma.user_appUncheckedCreateWithoutFuncionarioInput> | Prisma.user_appCreateWithoutFuncionarioInput[] | Prisma.user_appUncheckedCreateWithoutFuncionarioInput[]
  connectOrCreate?: Prisma.user_appCreateOrConnectWithoutFuncionarioInput | Prisma.user_appCreateOrConnectWithoutFuncionarioInput[]
  upsert?: Prisma.user_appUpsertWithWhereUniqueWithoutFuncionarioInput | Prisma.user_appUpsertWithWhereUniqueWithoutFuncionarioInput[]
  createMany?: Prisma.user_appCreateManyFuncionarioInputEnvelope
  set?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
  disconnect?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
  delete?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
  connect?: Prisma.user_appWhereUniqueInput | Prisma.user_appWhereUniqueInput[]
  update?: Prisma.user_appUpdateWithWhereUniqueWithoutFuncionarioInput | Prisma.user_appUpdateWithWhereUniqueWithoutFuncionarioInput[]
  updateMany?: Prisma.user_appUpdateManyWithWhereWithoutFuncionarioInput | Prisma.user_appUpdateManyWithWhereWithoutFuncionarioInput[]
  deleteMany?: Prisma.user_appScalarWhereInput | Prisma.user_appScalarWhereInput[]
}

export type user_appCreateNestedOneWithoutAplicacao_user_appInput = {
  create?: Prisma.XOR<Prisma.user_appCreateWithoutAplicacao_user_appInput, Prisma.user_appUncheckedCreateWithoutAplicacao_user_appInput>
  connectOrCreate?: Prisma.user_appCreateOrConnectWithoutAplicacao_user_appInput
  connect?: Prisma.user_appWhereUniqueInput
}

export type user_appUpdateOneRequiredWithoutAplicacao_user_appNestedInput = {
  create?: Prisma.XOR<Prisma.user_appCreateWithoutAplicacao_user_appInput, Prisma.user_appUncheckedCreateWithoutAplicacao_user_appInput>
  connectOrCreate?: Prisma.user_appCreateOrConnectWithoutAplicacao_user_appInput
  upsert?: Prisma.user_appUpsertWithoutAplicacao_user_appInput
  connect?: Prisma.user_appWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.user_appUpdateToOneWithWhereWithoutAplicacao_user_appInput, Prisma.user_appUpdateWithoutAplicacao_user_appInput>, Prisma.user_appUncheckedUpdateWithoutAplicacao_user_appInput>
}

export type user_appCreateWithoutFuncionarioInput = {
  username: string
  senha: string
  aplicacao_user_app?: Prisma.aplicacao_user_appCreateNestedManyWithoutUser_appInput
}

export type user_appUncheckedCreateWithoutFuncionarioInput = {
  id_user_app?: number
  username: string
  senha: string
  aplicacao_user_app?: Prisma.aplicacao_user_appUncheckedCreateNestedManyWithoutUser_appInput
}

export type user_appCreateOrConnectWithoutFuncionarioInput = {
  where: Prisma.user_appWhereUniqueInput
  create: Prisma.XOR<Prisma.user_appCreateWithoutFuncionarioInput, Prisma.user_appUncheckedCreateWithoutFuncionarioInput>
}

export type user_appCreateManyFuncionarioInputEnvelope = {
  data: Prisma.user_appCreateManyFuncionarioInput | Prisma.user_appCreateManyFuncionarioInput[]
  skipDuplicates?: boolean
}

export type user_appUpsertWithWhereUniqueWithoutFuncionarioInput = {
  where: Prisma.user_appWhereUniqueInput
  update: Prisma.XOR<Prisma.user_appUpdateWithoutFuncionarioInput, Prisma.user_appUncheckedUpdateWithoutFuncionarioInput>
  create: Prisma.XOR<Prisma.user_appCreateWithoutFuncionarioInput, Prisma.user_appUncheckedCreateWithoutFuncionarioInput>
}

export type user_appUpdateWithWhereUniqueWithoutFuncionarioInput = {
  where: Prisma.user_appWhereUniqueInput
  data: Prisma.XOR<Prisma.user_appUpdateWithoutFuncionarioInput, Prisma.user_appUncheckedUpdateWithoutFuncionarioInput>
}

export type user_appUpdateManyWithWhereWithoutFuncionarioInput = {
  where: Prisma.user_appScalarWhereInput
  data: Prisma.XOR<Prisma.user_appUpdateManyMutationInput, Prisma.user_appUncheckedUpdateManyWithoutFuncionarioInput>
}

export type user_appScalarWhereInput = {
  AND?: Prisma.user_appScalarWhereInput | Prisma.user_appScalarWhereInput[]
  OR?: Prisma.user_appScalarWhereInput[]
  NOT?: Prisma.user_appScalarWhereInput | Prisma.user_appScalarWhereInput[]
  id_user_app?: Prisma.IntFilter<"user_app"> | number
  username?: Prisma.StringFilter<"user_app"> | string
  senha?: Prisma.StringFilter<"user_app"> | string
  matricula_funcionario?: Prisma.StringNullableFilter<"user_app"> | string | null
}

export type user_appCreateWithoutAplicacao_user_appInput = {
  username: string
  senha: string
  funcionario?: Prisma.funcionarioCreateNestedOneWithoutUser_appsInput
}

export type user_appUncheckedCreateWithoutAplicacao_user_appInput = {
  id_user_app?: number
  username: string
  senha: string
  matricula_funcionario?: string | null
}

export type user_appCreateOrConnectWithoutAplicacao_user_appInput = {
  where: Prisma.user_appWhereUniqueInput
  create: Prisma.XOR<Prisma.user_appCreateWithoutAplicacao_user_appInput, Prisma.user_appUncheckedCreateWithoutAplicacao_user_appInput>
}

export type user_appUpsertWithoutAplicacao_user_appInput = {
  update: Prisma.XOR<Prisma.user_appUpdateWithoutAplicacao_user_appInput, Prisma.user_appUncheckedUpdateWithoutAplicacao_user_appInput>
  create: Prisma.XOR<Prisma.user_appCreateWithoutAplicacao_user_appInput, Prisma.user_appUncheckedCreateWithoutAplicacao_user_appInput>
  where?: Prisma.user_appWhereInput
}

export type user_appUpdateToOneWithWhereWithoutAplicacao_user_appInput = {
  where?: Prisma.user_appWhereInput
  data: Prisma.XOR<Prisma.user_appUpdateWithoutAplicacao_user_appInput, Prisma.user_appUncheckedUpdateWithoutAplicacao_user_appInput>
}

export type user_appUpdateWithoutAplicacao_user_appInput = {
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  funcionario?: Prisma.funcionarioUpdateOneWithoutUser_appsNestedInput
}

export type user_appUncheckedUpdateWithoutAplicacao_user_appInput = {
  id_user_app?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  matricula_funcionario?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type user_appCreateManyFuncionarioInput = {
  id_user_app?: number
  username: string
  senha: string
}

export type user_appUpdateWithoutFuncionarioInput = {
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  aplicacao_user_app?: Prisma.aplicacao_user_appUpdateManyWithoutUser_appNestedInput
}

export type user_appUncheckedUpdateWithoutFuncionarioInput = {
  id_user_app?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
  aplicacao_user_app?: Prisma.aplicacao_user_appUncheckedUpdateManyWithoutUser_appNestedInput
}

export type user_appUncheckedUpdateManyWithoutFuncionarioInput = {
  id_user_app?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  senha?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type User_appCountOutputType
 */

export type User_appCountOutputType = {
  aplicacao_user_app: number
}

export type User_appCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  aplicacao_user_app?: boolean | User_appCountOutputTypeCountAplicacao_user_appArgs
}

/**
 * User_appCountOutputType without action
 */
export type User_appCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User_appCountOutputType
   */
  select?: Prisma.User_appCountOutputTypeSelect<ExtArgs> | null
}

/**
 * User_appCountOutputType without action
 */
export type User_appCountOutputTypeCountAplicacao_user_appArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.aplicacao_user_appWhereInput
}


export type user_appSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_user_app?: boolean
  username?: boolean
  senha?: boolean
  matricula_funcionario?: boolean
  funcionario?: boolean | Prisma.user_app$funcionarioArgs<ExtArgs>
  aplicacao_user_app?: boolean | Prisma.user_app$aplicacao_user_appArgs<ExtArgs>
  _count?: boolean | Prisma.User_appCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user_app"]>

export type user_appSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_user_app?: boolean
  username?: boolean
  senha?: boolean
  matricula_funcionario?: boolean
  funcionario?: boolean | Prisma.user_app$funcionarioArgs<ExtArgs>
}, ExtArgs["result"]["user_app"]>

export type user_appSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id_user_app?: boolean
  username?: boolean
  senha?: boolean
  matricula_funcionario?: boolean
  funcionario?: boolean | Prisma.user_app$funcionarioArgs<ExtArgs>
}, ExtArgs["result"]["user_app"]>

export type user_appSelectScalar = {
  id_user_app?: boolean
  username?: boolean
  senha?: boolean
  matricula_funcionario?: boolean
}

export type user_appOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id_user_app" | "username" | "senha" | "matricula_funcionario", ExtArgs["result"]["user_app"]>
export type user_appInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  funcionario?: boolean | Prisma.user_app$funcionarioArgs<ExtArgs>
  aplicacao_user_app?: boolean | Prisma.user_app$aplicacao_user_appArgs<ExtArgs>
  _count?: boolean | Prisma.User_appCountOutputTypeDefaultArgs<ExtArgs>
}
export type user_appIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  funcionario?: boolean | Prisma.user_app$funcionarioArgs<ExtArgs>
}
export type user_appIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  funcionario?: boolean | Prisma.user_app$funcionarioArgs<ExtArgs>
}

export type $user_appPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "user_app"
  objects: {
    funcionario: Prisma.$funcionarioPayload<ExtArgs> | null
    aplicacao_user_app: Prisma.$aplicacao_user_appPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id_user_app: number
    username: string
    senha: string
    matricula_funcionario: string | null
  }, ExtArgs["result"]["user_app"]>
  composites: {}
}

export type user_appGetPayload<S extends boolean | null | undefined | user_appDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$user_appPayload, S>

export type user_appCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<user_appFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: User_appCountAggregateInputType | true
  }

export interface user_appDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['user_app'], meta: { name: 'user_app' } }
  /**
   * Find zero or one User_app that matches the filter.
   * @param {user_appFindUniqueArgs} args - Arguments to find a User_app
   * @example
   * // Get one User_app
   * const user_app = await prisma.user_app.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends user_appFindUniqueArgs>(args: Prisma.SelectSubset<T, user_appFindUniqueArgs<ExtArgs>>): Prisma.Prisma__user_appClient<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User_app that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {user_appFindUniqueOrThrowArgs} args - Arguments to find a User_app
   * @example
   * // Get one User_app
   * const user_app = await prisma.user_app.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends user_appFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, user_appFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_appClient<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_app that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_appFindFirstArgs} args - Arguments to find a User_app
   * @example
   * // Get one User_app
   * const user_app = await prisma.user_app.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends user_appFindFirstArgs>(args?: Prisma.SelectSubset<T, user_appFindFirstArgs<ExtArgs>>): Prisma.Prisma__user_appClient<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User_app that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_appFindFirstOrThrowArgs} args - Arguments to find a User_app
   * @example
   * // Get one User_app
   * const user_app = await prisma.user_app.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends user_appFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, user_appFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__user_appClient<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more User_apps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_appFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all User_apps
   * const user_apps = await prisma.user_app.findMany()
   * 
   * // Get first 10 User_apps
   * const user_apps = await prisma.user_app.findMany({ take: 10 })
   * 
   * // Only select the `id_user_app`
   * const user_appWithId_user_appOnly = await prisma.user_app.findMany({ select: { id_user_app: true } })
   * 
   */
  findMany<T extends user_appFindManyArgs>(args?: Prisma.SelectSubset<T, user_appFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User_app.
   * @param {user_appCreateArgs} args - Arguments to create a User_app.
   * @example
   * // Create one User_app
   * const User_app = await prisma.user_app.create({
   *   data: {
   *     // ... data to create a User_app
   *   }
   * })
   * 
   */
  create<T extends user_appCreateArgs>(args: Prisma.SelectSubset<T, user_appCreateArgs<ExtArgs>>): Prisma.Prisma__user_appClient<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many User_apps.
   * @param {user_appCreateManyArgs} args - Arguments to create many User_apps.
   * @example
   * // Create many User_apps
   * const user_app = await prisma.user_app.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends user_appCreateManyArgs>(args?: Prisma.SelectSubset<T, user_appCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many User_apps and returns the data saved in the database.
   * @param {user_appCreateManyAndReturnArgs} args - Arguments to create many User_apps.
   * @example
   * // Create many User_apps
   * const user_app = await prisma.user_app.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many User_apps and only return the `id_user_app`
   * const user_appWithId_user_appOnly = await prisma.user_app.createManyAndReturn({
   *   select: { id_user_app: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends user_appCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, user_appCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User_app.
   * @param {user_appDeleteArgs} args - Arguments to delete one User_app.
   * @example
   * // Delete one User_app
   * const User_app = await prisma.user_app.delete({
   *   where: {
   *     // ... filter to delete one User_app
   *   }
   * })
   * 
   */
  delete<T extends user_appDeleteArgs>(args: Prisma.SelectSubset<T, user_appDeleteArgs<ExtArgs>>): Prisma.Prisma__user_appClient<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User_app.
   * @param {user_appUpdateArgs} args - Arguments to update one User_app.
   * @example
   * // Update one User_app
   * const user_app = await prisma.user_app.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends user_appUpdateArgs>(args: Prisma.SelectSubset<T, user_appUpdateArgs<ExtArgs>>): Prisma.Prisma__user_appClient<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more User_apps.
   * @param {user_appDeleteManyArgs} args - Arguments to filter User_apps to delete.
   * @example
   * // Delete a few User_apps
   * const { count } = await prisma.user_app.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends user_appDeleteManyArgs>(args?: Prisma.SelectSubset<T, user_appDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_apps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_appUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many User_apps
   * const user_app = await prisma.user_app.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends user_appUpdateManyArgs>(args: Prisma.SelectSubset<T, user_appUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more User_apps and returns the data updated in the database.
   * @param {user_appUpdateManyAndReturnArgs} args - Arguments to update many User_apps.
   * @example
   * // Update many User_apps
   * const user_app = await prisma.user_app.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more User_apps and only return the `id_user_app`
   * const user_appWithId_user_appOnly = await prisma.user_app.updateManyAndReturn({
   *   select: { id_user_app: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends user_appUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, user_appUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User_app.
   * @param {user_appUpsertArgs} args - Arguments to update or create a User_app.
   * @example
   * // Update or create a User_app
   * const user_app = await prisma.user_app.upsert({
   *   create: {
   *     // ... data to create a User_app
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User_app we want to update
   *   }
   * })
   */
  upsert<T extends user_appUpsertArgs>(args: Prisma.SelectSubset<T, user_appUpsertArgs<ExtArgs>>): Prisma.Prisma__user_appClient<runtime.Types.Result.GetResult<Prisma.$user_appPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of User_apps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_appCountArgs} args - Arguments to filter User_apps to count.
   * @example
   * // Count the number of User_apps
   * const count = await prisma.user_app.count({
   *   where: {
   *     // ... the filter for the User_apps we want to count
   *   }
   * })
  **/
  count<T extends user_appCountArgs>(
    args?: Prisma.Subset<T, user_appCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], User_appCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User_app.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {User_appAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends User_appAggregateArgs>(args: Prisma.Subset<T, User_appAggregateArgs>): Prisma.PrismaPromise<GetUser_appAggregateType<T>>

  /**
   * Group by User_app.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {user_appGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends user_appGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: user_appGroupByArgs['orderBy'] }
      : { orderBy?: user_appGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, user_appGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUser_appGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the user_app model
 */
readonly fields: user_appFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for user_app.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__user_appClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  funcionario<T extends Prisma.user_app$funcionarioArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.user_app$funcionarioArgs<ExtArgs>>): Prisma.Prisma__funcionarioClient<runtime.Types.Result.GetResult<Prisma.$funcionarioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  aplicacao_user_app<T extends Prisma.user_app$aplicacao_user_appArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.user_app$aplicacao_user_appArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$aplicacao_user_appPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the user_app model
 */
export interface user_appFieldRefs {
  readonly id_user_app: Prisma.FieldRef<"user_app", 'Int'>
  readonly username: Prisma.FieldRef<"user_app", 'String'>
  readonly senha: Prisma.FieldRef<"user_app", 'String'>
  readonly matricula_funcionario: Prisma.FieldRef<"user_app", 'String'>
}
    

// Custom InputTypes
/**
 * user_app findUnique
 */
export type user_appFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * Filter, which user_app to fetch.
   */
  where: Prisma.user_appWhereUniqueInput
}

/**
 * user_app findUniqueOrThrow
 */
export type user_appFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * Filter, which user_app to fetch.
   */
  where: Prisma.user_appWhereUniqueInput
}

/**
 * user_app findFirst
 */
export type user_appFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * Filter, which user_app to fetch.
   */
  where?: Prisma.user_appWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_apps to fetch.
   */
  orderBy?: Prisma.user_appOrderByWithRelationInput | Prisma.user_appOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_apps.
   */
  cursor?: Prisma.user_appWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_apps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_apps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_apps.
   */
  distinct?: Prisma.User_appScalarFieldEnum | Prisma.User_appScalarFieldEnum[]
}

/**
 * user_app findFirstOrThrow
 */
export type user_appFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * Filter, which user_app to fetch.
   */
  where?: Prisma.user_appWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_apps to fetch.
   */
  orderBy?: Prisma.user_appOrderByWithRelationInput | Prisma.user_appOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for user_apps.
   */
  cursor?: Prisma.user_appWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_apps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_apps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of user_apps.
   */
  distinct?: Prisma.User_appScalarFieldEnum | Prisma.User_appScalarFieldEnum[]
}

/**
 * user_app findMany
 */
export type user_appFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * Filter, which user_apps to fetch.
   */
  where?: Prisma.user_appWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of user_apps to fetch.
   */
  orderBy?: Prisma.user_appOrderByWithRelationInput | Prisma.user_appOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing user_apps.
   */
  cursor?: Prisma.user_appWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` user_apps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` user_apps.
   */
  skip?: number
  distinct?: Prisma.User_appScalarFieldEnum | Prisma.User_appScalarFieldEnum[]
}

/**
 * user_app create
 */
export type user_appCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * The data needed to create a user_app.
   */
  data: Prisma.XOR<Prisma.user_appCreateInput, Prisma.user_appUncheckedCreateInput>
}

/**
 * user_app createMany
 */
export type user_appCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many user_apps.
   */
  data: Prisma.user_appCreateManyInput | Prisma.user_appCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * user_app createManyAndReturn
 */
export type user_appCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * The data used to create many user_apps.
   */
  data: Prisma.user_appCreateManyInput | Prisma.user_appCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * user_app update
 */
export type user_appUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * The data needed to update a user_app.
   */
  data: Prisma.XOR<Prisma.user_appUpdateInput, Prisma.user_appUncheckedUpdateInput>
  /**
   * Choose, which user_app to update.
   */
  where: Prisma.user_appWhereUniqueInput
}

/**
 * user_app updateMany
 */
export type user_appUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update user_apps.
   */
  data: Prisma.XOR<Prisma.user_appUpdateManyMutationInput, Prisma.user_appUncheckedUpdateManyInput>
  /**
   * Filter which user_apps to update
   */
  where?: Prisma.user_appWhereInput
  /**
   * Limit how many user_apps to update.
   */
  limit?: number
}

/**
 * user_app updateManyAndReturn
 */
export type user_appUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * The data used to update user_apps.
   */
  data: Prisma.XOR<Prisma.user_appUpdateManyMutationInput, Prisma.user_appUncheckedUpdateManyInput>
  /**
   * Filter which user_apps to update
   */
  where?: Prisma.user_appWhereInput
  /**
   * Limit how many user_apps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * user_app upsert
 */
export type user_appUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * The filter to search for the user_app to update in case it exists.
   */
  where: Prisma.user_appWhereUniqueInput
  /**
   * In case the user_app found by the `where` argument doesn't exist, create a new user_app with this data.
   */
  create: Prisma.XOR<Prisma.user_appCreateInput, Prisma.user_appUncheckedCreateInput>
  /**
   * In case the user_app was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.user_appUpdateInput, Prisma.user_appUncheckedUpdateInput>
}

/**
 * user_app delete
 */
export type user_appDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
  /**
   * Filter which user_app to delete.
   */
  where: Prisma.user_appWhereUniqueInput
}

/**
 * user_app deleteMany
 */
export type user_appDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which user_apps to delete
   */
  where?: Prisma.user_appWhereInput
  /**
   * Limit how many user_apps to delete.
   */
  limit?: number
}

/**
 * user_app.funcionario
 */
export type user_app$funcionarioArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the funcionario
   */
  select?: Prisma.funcionarioSelect<ExtArgs> | null
  /**
   * Omit specific fields from the funcionario
   */
  omit?: Prisma.funcionarioOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.funcionarioInclude<ExtArgs> | null
  where?: Prisma.funcionarioWhereInput
}

/**
 * user_app.aplicacao_user_app
 */
export type user_app$aplicacao_user_appArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the aplicacao_user_app
   */
  select?: Prisma.aplicacao_user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the aplicacao_user_app
   */
  omit?: Prisma.aplicacao_user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.aplicacao_user_appInclude<ExtArgs> | null
  where?: Prisma.aplicacao_user_appWhereInput
  orderBy?: Prisma.aplicacao_user_appOrderByWithRelationInput | Prisma.aplicacao_user_appOrderByWithRelationInput[]
  cursor?: Prisma.aplicacao_user_appWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Aplicacao_user_appScalarFieldEnum | Prisma.Aplicacao_user_appScalarFieldEnum[]
}

/**
 * user_app without action
 */
export type user_appDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the user_app
   */
  select?: Prisma.user_appSelect<ExtArgs> | null
  /**
   * Omit specific fields from the user_app
   */
  omit?: Prisma.user_appOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.user_appInclude<ExtArgs> | null
}
